-- MySQL Script generated by MySQL Workbench
-- sex 15 nov 2019 16:01:10 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_atom_definitivo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_atom_definitivo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_atom_definitivo` DEFAULT CHARACTER SET utf8 ;
USE `bd_atom_definitivo` ;

-- -----------------------------------------------------
-- Table `bd_atom_definitivo`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom_definitivo`.`alunos` (
  `codAluno` INT(5) NOT NULL AUTO_INCREMENT,
  `nomeAluno` VARCHAR(180) NULL DEFAULT NULL,
  `imgAluno` VARCHAR(540) NULL DEFAULT NULL,
  `dataNasc` DATE NULL DEFAULT NULL,
  `curso` VARCHAR(180) NULL DEFAULT NULL,
  `email` VARCHAR(180) NOT NULL,
  `senha` VARCHAR(180) NOT NULL,
  `anoLetivo` VARCHAR(180) NULL DEFAULT NULL,
  `tipo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`codAluno`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_atom_definitivo`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom_definitivo`.`disciplinas` (
  `codDisciplina` INT(5) NOT NULL AUTO_INCREMENT,
  `nomeDisciplina` VARCHAR(180) NULL DEFAULT NULL,
  `imgDisciplina` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codDisciplina`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_atom_definitivo`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom_definitivo`.`professores` (
  `codProfessor` INT(5) NOT NULL AUTO_INCREMENT,
  `imgProfessor` VARCHAR(540) NULL DEFAULT NULL,
  `email` VARCHAR(180) NOT NULL,
  `miniCurriculo` VARCHAR(240) NULL DEFAULT NULL,
  `instituicao` VARCHAR(180) NULL DEFAULT NULL,
  `dataNasc` DATE NULL DEFAULT NULL,
  `senha` VARCHAR(180) NOT NULL,
  `nomeProfessor` VARCHAR(180) NOT NULL,
  `tipo` TINYINT(1) NULL DEFAULT NULL,
  `admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`codProfessor`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_atom_definitivo`.`artigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom_definitivo`.`artigos` (
  `codArtigo` INT(11) NOT NULL AUTO_INCREMENT,
  `dataArtigo` DATETIME NULL DEFAULT NULL,
  `titulo` VARCHAR(180) NOT NULL,
  `imgArtigo` VARCHAR(45) NULL DEFAULT NULL,
  `uploadArtigo` VARCHAR(540) NULL DEFAULT NULL,
  `disciplina_codDisciplina` INT(5) NOT NULL,
  `professores_codProfessor` INT(5) NULL DEFAULT NULL,
  `alunos_codAluno` INT(5) NULL DEFAULT NULL,
  `corpo` LONGTEXT NOT NULL,
  `resumo` VARCHAR(240) NOT NULL,
  PRIMARY KEY (`codArtigo`),
  INDEX `fk_artigo_disciplina1_idx` (`disciplina_codDisciplina` ASC),
  INDEX `fk_artigo_professores1_idx` (`professores_codProfessor` ASC),
  INDEX `fk_artigo_alunos1_idx` (`alunos_codAluno` ASC),
  CONSTRAINT `fk_artigo_alunos1`
    FOREIGN KEY (`alunos_codAluno`)
    REFERENCES `bd_atom_definitivo`.`alunos` (`codAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artigo_disciplina1`
    FOREIGN KEY (`disciplina_codDisciplina`)
    REFERENCES `bd_atom_definitivo`.`disciplinas` (`codDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artigo_professores1`
    FOREIGN KEY (`professores_codProfessor`)
    REFERENCES `bd_atom_definitivo`.`professores` (`codProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 109
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_atom_definitivo`.`professores_has_disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom_definitivo`.`professores_has_disciplinas` (
  `professores_codProfessor` INT(5) NOT NULL,
  `disciplina_codDisciplina` INT(5) NOT NULL,
  PRIMARY KEY (`professores_codProfessor`, `disciplina_codDisciplina`),
  INDEX `fk_professores_has_disciplina_disciplina1_idx` (`disciplina_codDisciplina` ASC),
  INDEX `fk_professores_has_disciplina_professores1_idx` (`professores_codProfessor` ASC),
  CONSTRAINT `fk_professores_has_disciplina_disciplina1`
    FOREIGN KEY (`disciplina_codDisciplina`)
    REFERENCES `bd_atom_definitivo`.`disciplinas` (`codDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professores_has_disciplina_professores1`
    FOREIGN KEY (`professores_codProfessor`)
    REFERENCES `bd_atom_definitivo`.`professores` (`codProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bd_atom_definitivo`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom_definitivo`.`comentarios` (
  `codComentario` INT NOT NULL,
  `dataComentario` DATE NULL,
  `comentario` VARCHAR(240) NULL,
  `com_professores_codProfessor` INT(5) NULL,
  `com_alunos_codAluno` INT(5) NULL,
  `artigos_codArtigo` INT(11) NOT NULL,
  PRIMARY KEY (`codComentario`),
  INDEX `fk_comentarios_professores1_idx` (`com_professores_codProfessor` ASC),
  INDEX `fk_comentarios_alunos1_idx` (`com_alunos_codAluno` ASC),
  INDEX `fk_comentarios_artigos1_idx` (`artigos_codArtigo` ASC),
  CONSTRAINT `fk_comentarios_professores1`
    FOREIGN KEY (`com_professores_codProfessor`)
    REFERENCES `bd_atom_definitivo`.`professores` (`codProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_alunos1`
    FOREIGN KEY (`com_alunos_codAluno`)
    REFERENCES `bd_atom_definitivo`.`alunos` (`codAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_artigos1`
    FOREIGN KEY (`artigos_codArtigo`)
    REFERENCES `bd_atom_definitivo`.`artigos` (`codArtigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
