-- MySQL Script generated by MySQL Workbench
-- sáb 14 set 2019 07:45:09 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_atom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_atom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_atom` DEFAULT CHARACTER SET utf8 ;
USE `bd_atom` ;

-- -----------------------------------------------------
-- Table `bd_atom`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom`.`alunos` (
  `codAluno` INT(5) NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(180) NULL DEFAULT NULL,
  `dataNasc` DATE NULL DEFAULT NULL,
  `imgAluno` VARCHAR(180) NULL DEFAULT NULL,
  `anoLetivo` VARCHAR(100) NULL DEFAULT NULL,
  `curso` VARCHAR(180) NULL DEFAULT NULL,
  `email` VARCHAR(500) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`codAluno`))
ENGINE = MyISAM
AUTO_INCREMENT = 85
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_atom`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom`.`professores` (
  `codProfessor` INT(5) NOT NULL AUTO_INCREMENT,
  `imgProfessor` VARCHAR(180) NULL DEFAULT NULL,
  `email` VARCHAR(180) NULL DEFAULT NULL,
  `miniCurriculo` VARCHAR(240) NULL DEFAULT NULL,
  `institucao` VARCHAR(180) NULL DEFAULT NULL,
  `nomeCompleto` VARCHAR(180) NULL DEFAULT NULL,
  `dataNasc` DATE NULL DEFAULT NULL,
  `cod_exercicio` INT(5) NULL DEFAULT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `area` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codProfessor`),
  INDEX `cod_exercicio` (`cod_exercicio` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_atom`.`artigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom`.`artigos` (
  `codArtigo` INT(5) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(180) NULL DEFAULT NULL,
  `corpo` TEXT NULL DEFAULT NULL,
  `imgArtigo` VARCHAR(200) NOT NULL,
  `uploadArtigo` VARCHAR(200) NULL DEFAULT NULL,
  `alunos_codAluno` INT(5) NOT NULL,
  `professores_codProfessor` INT(5) NOT NULL,
  PRIMARY KEY (`codArtigo`, `alunos_codAluno`, `professores_codProfessor`),
  INDEX `fk_artigos_alunos1_idx` (`alunos_codAluno` ASC),
  INDEX `fk_artigos_professores1_idx` (`professores_codProfessor` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_atom`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom`.`comentario` (
  `codComentario` INT(5) NOT NULL AUTO_INCREMENT,
  `data` DATE NULL DEFAULT NULL,
  `comentario` VARCHAR(240) NULL DEFAULT NULL,
  `codVideo` INT(5) NULL DEFAULT NULL,
  `codAluno` INT(5) NULL DEFAULT NULL,
  `artigos_codArtigo` INT(5) NOT NULL,
  `alunos_codAluno` INT(5) NOT NULL,
  `professores_codProfessor` INT(5) NOT NULL,
  PRIMARY KEY (`codComentario`, `artigos_codArtigo`, `alunos_codAluno`, `professores_codProfessor`),
  INDEX `codVideo` (`codVideo` ASC),
  INDEX `codAluno` (`codAluno` ASC),
  INDEX `fk_comentario_artigos1_idx` (`artigos_codArtigo` ASC),
  INDEX `fk_comentario_alunos1_idx` (`alunos_codAluno` ASC),
  INDEX `fk_comentario_professores1_idx` (`professores_codProfessor` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_atom`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom`.`disciplinas` (
  `codDisciplina` INT(5) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(180) NULL DEFAULT NULL,
  PRIMARY KEY (`codDisciplina`))
ENGINE = MyISAM
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_atom`.`artigos_has_disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom`.`artigos_has_disciplinas` (
  `artigos_codArtigo` INT(5) NOT NULL,
  `disciplinas_codDisciplina` INT(5) NOT NULL,
  PRIMARY KEY (`artigos_codArtigo`, `disciplinas_codDisciplina`),
  INDEX `fk_artigos_has_disciplinas_disciplinas1_idx` (`disciplinas_codDisciplina` ASC),
  INDEX `fk_artigos_has_disciplinas_artigos1_idx` (`artigos_codArtigo` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_atom`.`professores_has_disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_atom`.`professores_has_disciplinas` (
  `professores_codProfessor` INT(5) NOT NULL,
  `disciplinas_codDisciplina` INT(5) NOT NULL,
  PRIMARY KEY (`professores_codProfessor`, `disciplinas_codDisciplina`),
  INDEX `fk_professores_has_disciplinas_disciplinas1_idx` (`disciplinas_codDisciplina` ASC),
  INDEX `fk_professores_has_disciplinas_professores1_idx` (`professores_codProfessor` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
